import type { Metadata } from 'next';
import { Noto_Sans, Noto_Sans_Mono } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({ variable: '--font-sans' });

const notoSansMono = Noto_Sans_Mono({ variable: '--font-noto-sans-mono' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body
        className={`${notoSans.variable} ${notoSansMono.variable} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
