import type { Metadata } from 'next';
import { Oswald, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-family-inter',
});

const oswald = Oswald({
  variable: '--font-family-oswald',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${oswald.variable}`}>
      <body className="antialiased">
        <Header />
        <div className="min-h-svh pt-20 relative">{children}</div>
      </body>
    </html>
  );
}
